### ISSUE TITLE
Prefer locally-installed node-gyp

### ISSUE THREAD

**Issue by vweevers** [prebuild/prebuildify#30]
Currently, `prebuildify` uses the `node-gyp` that's available in `PATH` and when `npm` runs scripts, it adds the global `node_modules/npm-lifecycle/node-gyp-bin` folder to `PATH`. Effectively, we're always using the npm-bundled version of `node-gyp`.

**Comment by vweevers** [comment]
@mafintosh @emilbayes @lpinca @lgeiger Any objections?

(Apologies if I've wrongly identified you as a `prebuildify` user)

**Comment by mafintosh** [comment]
@vweevers i thought npm prefixed the path with the local ones?

if not, yea if it can be done simply then 👍 obvs :)

**Comment by vweevers** [comment]
> i thought npm prefixed the path with the local ones?

It still does that, but the path to the bundled `node-gyp` [takes precedence](https://github.com/npm/npm-lifecycle/blob/cf5f5ca6d2bd095cffc0b995195a688df644dded/index.js#L112-L116) over that local `.bin` folder. This has been the case since npm [5.6.0](https://github.com/npm/cli/blob/latest/changelogs/CHANGELOG-5.md#v560-2017-11-27) (surprised me as well).

**Comment by mafintosh** [comment]
That's lame 👎 All for supporting that.

**Comment by lpinca** [comment]
No objections.
