### ISSUE TITLE
Distributing N-API modules for different linux distributions

### ISSUE THREAD

**Issue by alcuadrado** [prebuild/prebuildify#40]
Hi,

I'm using an npm package that is built using this project, and run into [this issue](https://github.com/cryptocoinjs/keccak/issues/15) which I'm trying to fix. 

The problem is that the package is built and linked with `glibc`, and some users are trying to run it on Alpine, which uses the `musl` libc. I understand that this combination is not meant to work, and wonder what's your recommended way for dealing with this.

I have a few options in mind:

1. Link the libc statically for Linux distributions.
2. Have separate prebuilds for glibc- and musllibc-based systems.
3. Fallback to a js implementation in musllibc-based systems.

I'd say that my personal preference would be (1), but I'd love to know your opinions. I'm not exactly sure how any option would be implemented. 

Can you please help me with this? 

Thanks!

**Comment by vweevers** [comment]
A fourth option would be to pass `--tag-libc` to `prebuildify`. This way the prebuild name will include `.glibc` and be skipped on alpine. An `npm install` will then fall back to compiling from source. This can also be done manually with `npm i --build-from-source`.

As for option 2, see [`prebuildify-cross`](https://github.com/prebuild/prebuildify-cross) which can compile a prebuild in an alpine docker image. For an example see [`leveldown`](https://github.com/Level/leveldown).

**Comment by alcuadrado** [comment]
Oh, that's great, @vweevers! I guess we should use both `--tag-libc` and `prebuildify-cross`.

Thanks for the quick answer and for linking an example!

**Comment by fanatid** [comment]
[prebuildify-cross](https://github.com/prebuild/prebuildify-cross) should be installed from github? On npm latest version is `3.1.2` https://www.npmjs.com/package/prebuildify-cross

**Comment by vweevers** [comment]
@fanatid https://github.com/prebuild/prebuildify-cross/issues/8
