### ISSUE TITLE
Building for Node v12.18 produces wrong ABI version

### ISSUE THREAD

**Issue by kriszyp** [prebuild/prebuildify#43]
If I prebuildify with Node v12 as a target:

`prebuildify --target 12.18.0`

It seems to properly build the right binary, but it saves the file as `node.abi68.node`, which is not the correct ABI version, the correct ABI version for Node v12.18 is 72 (https://nodejs.org/en/download/releases/), so when user attempts to run the module in Node v12, it says there is no native build available (or builds/compiles as a fallback during installation).

This seems to be the case for any platform I specify.

**Comment by kriszyp** [comment]
I guess this is actually due to https://github.com/lgeiger/node-abi/issues/90

**Comment by ludiazv** [comment]
This also affects node 13 & 14.
 There is a PR on node-abi to solve but still not merged or published. https://github.com/lgeiger/node-abi/pull/95#issue-492515557
