### ISSUE TITLE
Naming of fat binaries for M1 (Apple silicon)

### ISSUE THREAD

**Issue by vweevers** [prebuild/prebuildify#52]
In order to support M1 (Apple silicon), addon authors can build so-called fat binaries, that work on both x86_64 and arm64. This seems like the easiest way to add M1 support. For example https://github.com/fsevents/fsevents/pull/350.

It's at odds with our current folder structure though. What would the `arch` be in e.g. `darwin-<arch>/node.napi.node`?

**Comment by vweevers** [comment]
Options:

1. Dual arch: `darwin-x64_arm64/*.node`. It'll be up to the addon author to setup their CI to produce this folder name.
2. Some special name like `darwin-universal/*.node`.
3. Same as today: `darwin-x64/*.node`. As a temporary solution, `node-gyp-build` could attempt to load this prebuild if `os.arch() === 'arm64'`. If it succeeds it must mean the prebuild is a fat binary.

**Comment by mafintosh** [comment]
@vweevers would copying it work? it's zipped anyway.

**Comment by vweevers** [comment]
I didn't try producing a fat binary yet but I assume it will be bigger than a single-arch binary (which on `rocksdb` for example is already 1.81 MB gzipped). So I would prefer not duplicating it.

**Comment by lpinca** [comment]
I'm fine with option 1.

**Comment by mafintosh** [comment]
yea 1) or 2) is fine with me as well.

**Comment by vweevers** [comment]
Let's go for option 1 then.

I wrote that "It'll be up to the addon author to setup their CI to produce this folder name" but perhaps prebuildify can do it. 

Somewhat tricky because although we currently take a custom `--arch` or `PREBUILD_ARCH` which affects the folder name, we would also forward that value to `node-gyp` (and thus gyp and thus binding.gyp) which will probably not like the value `x64_arm64`.

In addition, we do that forwarding via `node-gyp --target-arch`:

https://github.com/prebuild/prebuildify/blob/4f7194401252256b14d75d3c1614e9ba5d97dfee/index.js#L190

Which I think is no longer supported in `node-gyp` (according to docs and [a quick look at code](https://github.com/nodejs/node-gyp/blob/bc47cd60b986eaa55a23050d8f72d1cc117bdba0/lib/configure.js#L134)). We should be passing `--arch` instead.

On the other hand, if I'm right that `--target-arch` is ignored (since which version?) then we can avoid this problem for now. AFAICT `node-gyp` has no builtin support for fat binaries anyway; addon authors have to specify `-arch x86_64 -arch arm64` compiler flags in their `binding.gyp`.

**Comment by vweevers** [comment]
I checked, `--target-arch` does still work to some extent, thanks to [this](https://github.com/nodejs/node-gyp/blob/bc47cd60b986eaa55a23050d8f72d1cc117bdba0/lib/configure.js#L176), but we're missing out on earlier logic that's based on ` --arch` (for example [here](https://github.com/nodejs/node-gyp/blob/bc47cd60b986eaa55a23050d8f72d1cc117bdba0/lib/configure.js#L135-L138) and [here](https://github.com/nodejs/node-gyp/blob/bc47cd60b986eaa55a23050d8f72d1cc117bdba0/lib/configure.js#L154-L156)).

The node-gyp `--arch` option is documented since node-gyp@3.4.0 (https://github.com/nodejs/node-gyp/commit/4ee31329e0ee022e4cd094a193972b9c0bae8815) which is old enough (node 8.6.0 bundles node-gyp@3.6.2, fx).

So I propose we replace `--target-arch` with `--arch`. Using `arch.split('+')[0]` as the value (note that in https://github.com/prebuild/node-gyp-build/pull/40 we decided to use `+` as arch separator instead of `_`) so that we only pass the first arch to `node-gyp`. I will send a PR.

**Comment by vweevers** [comment]
Done in `node-gyp-build` 4.3.0 and `prebuildify` 4.2.1.
