### ISSUE TITLE
[Question] specify napi version

### ISSUE THREAD

**Issue by thegecko** [prebuild/prebuildify#58]
Apologies if I've missed some docs somewhere, but it isn't clear how to specify the napi version when using the `--napi` flag.

I assumed the target flag would be used, e.g. `--napi --target 4` similar to `prebuild`, but this results in an error:

```bash
TypeError: v.indexOf is not a function
```

It seems you need to find the earliest corresponding node version for the napi version you want instead from the [Node-API Version Matrix](https://nodejs.org/api/n-api.html#node-api-version-matrix), is that right?

So for napi 4 you specify `--napi --target 10.16.0`

Finally, is the default napi version used the latest available rather than the oldest. I'm keen to promote interoperability by building for the oldest Node API?

Cheers!

**Comment by vweevers** [comment]
(see https://nodejs.org/api/n-api.html#usage for `NAPI_VERSION`)

**Comment by thegecko** [comment]
OK, thanks!
