### ISSUE TITLE
--target electron@19.0.0 fails due to dist-url 403

### ISSUE THREAD

**Issue by simonbuchan** [prebuild/prebuildify#67]
Currently the dist-url for electron is `https://atom.io/download/electron`, but from `--target electron@19.0.0` (the current-ish version), it 403s. Note 18.0.0 works. Possibly related to Atom being killed?

It looks like [`electron-rebuilder` uses https://www.electronjs.org/headers](https://github.com/electron/electron-rebuild/blob/3f5ff99d4c7ae69053472b75f782e5ea776c2d80/src/rebuild.ts#L70), and indeed https://www.electronjs.org/headers/v19.0.8/node-v19.0.8-headers.tar.gz works.

**Comment by simonbuchan** [comment]
Note this would be easier to workaround if we could provide --dist-url, but `cross-env npm_config_dist_url=https://www.electronjs.org/headers prebuildify ...` does work.

**Comment by vweevers** [comment]
Needs the same fix as https://github.com/prebuild/prebuild/commit/506732cce6f15c43edd0be17ee3e5df12d54876b. PR is welcome.

**Comment by obfuscatedgenerated** [comment]
I spun up a quick PR when I came across this issue 😀
