### ISSUE TITLE
Does `napi` default to true or false? Docs think false.

### ISSUE THREAD

**Issue by jsumners-nr** [prebuild/prebuildify#77]
https://github.com/prebuild/prebuildify/blob/d6d6981efb3258e7de2f310c9bc1182f5842579d/README.md?plain=1#L86

This line is incorrect as far as I can tell:

https://github.com/prebuild/prebuildify/blob/d6d6981efb3258e7de2f310c9bc1182f5842579d/bin.js#L22-L24

Which caused me a lot of confusion until I discovered the following through some local debugging:

https://github.com/prebuild/prebuildify/issues/64#issuecomment-1133857448
> prebuildify is geared towards Node-API, so the version of the executing node process is not necessarily the right version. It defaults to compiling against the latest node version

**Comment by vweevers** [comment]
The default recently changed in https://github.com/prebuild/prebuildify/commit/4300cf4fcc3a6af4b97d46d314d1ab7e94c76af5 and we forgot to update the README. That should say `true`. PR welcome!
