### ISSUE TITLE
cross compiling isn't cross compiling on host=linux-x64, target=linux-arm64

### ISSUE THREAD

**Issue by toshok** [prebuild/prebuildify#94]
Filed [this](https://github.com/tree-sitter/workflows/issues/22) but they routed me here.  As alluded to there, prebuildify is generating an x64 .so even with the `--arch arm` arg.  Here's the line in their workflow:

```
run: npm x -- prebuildify --strip --arch arm64 --target 20.9.0 
```

I've also manually run `prebuildify-cross` using that command line but with `-i linux-arm64` as well, and still ended up with an x64 .so.  Hoping it's just me or something about the my setup locally.  has anyone cross compiled linux-arm64 prebuilds?

If not, any idea where to look for the problem?  I kinda expect the next place is `node-gyp`, but I'm hoping to avoid that if possible ;)  I'm willing to find/fix the problem but a little help at identifying the layer to focus on would be super helpful.

**Comment by vweevers** [comment]
Out of the box, `prebuildify` doesn't cross-compile, and you were right to look at `prebuildify-cross`.

> has anyone cross compiled linux-arm64 prebuilds?

Yes, [`classic-level`](https://github.com/Level/classic-level/blob/d142686a1ee4c2791ef1e2b40377e38e10d3e7c8/package.json#L22-L27) has 'em, [`serialport`](https://github.com/serialport/bindings-cpp) too I believe.

**Comment by toshok** [comment]
> Yes, [`classic-level`](https://github.com/Level/classic-level/blob/d142686a1ee4c2791ef1e2b40377e38e10d3e7c8/package.json#L22-L27) has 'em, [`serialport`](https://github.com/serialport/bindings-cpp) too I believe.

perfect.  I'll see if I can figure out differences between them and tree-sitter 👍

**Comment by ObserverOfTime** [comment]
Turns out we just had to set `CC` & `CXX` for node-gyp because prebuildify doesn't do it automatically.
